---
- hosts: localhost

  vars_files:
    - vars/main.yml
    - config.yml

  pre_tasks:
    - name: Prerequisite | Create output directories if they do not exist
      file:
        path: '{{ item }}'
        state: directory
      with_items:
        - '{{ playbook_dir }}/output/aidc'
        - '{{ playbook_dir }}/output/ibm'
        - '{{ playbook_dir }}/output/middlewares'

    - name: Prerequisite | Check if Helm is installed
      command: which helm
      register: helm_installed
      changed_when: false
      failed_when:
        - 'helm_installed.rc == 1'

    - import_tasks: tasks/prepare/main.yml

  tasks:
    - import_tasks: tasks/deploy-middlewares/main.yml

    - import_tasks: tasks/deploy-operators/main.yml
      when: ibm.operator.enabled|bool == true

    - import_tasks: tasks/deploy-applications/main.yml
