---
- name: Deploy - Phase 2 | Create Studio deployment
  kubernetes.core.k8s:
    src: '{{ playbook_dir }}/output/aidc/studio-app-deployment.yaml'
    state: present

- name: Deploy - Phase 2 | Wait for aidc-studio-deployment (6Os delay)
  kubernetes.core.k8s_info:
    kind: Deployment
    api_version: apps/v1
    name: aidc-studio-deployment
    namespace: '{{ oc.project.aidc }}'
  register: ibm_aidc_studio_deployment_lookup
  until: ibm_aidc_studio_deployment_lookup.resources[0].status.availableReplicas is defined
  retries: 10
  delay: 30

- name: Deploy - Phase 2 | Create Dispatch deployment
  kubernetes.core.k8s:
    src: '{{ playbook_dir }}/output/aidc/dispatch-app-deployment.yaml'
    state: present

- name: Deploy - Phase 2 | Wait for aidc-dispatch-deployment (6Os delay)
  kubernetes.core.k8s_info:
    kind: Deployment
    api_version: apps/v1
    name: aidc-dispatch-deployment
    namespace: '{{ oc.project.aidc }}'
  register: ibm_aidc_dispatch_deployment_lookup
  until: ibm_aidc_dispatch_deployment_lookup.resources[0].status.availableReplicas is defined
  retries: 10
  delay: 30
