---
- name: Deploy - Phase 2 | Install ibm-common-service-operator
  kubernetes.core.k8s:
    src: '{{ playbook_dir }}/output/ibm/ibm-common-service-operator.yaml'
    state: present

- name: Deploy - Phase 2 | Wait for ibm-common-service-operator to be ready (60s delay)
  kubernetes.core.k8s_info:
    kind: Deployment
    api_version: apps/v1
    name: ibm-common-service-operator
    namespace: '{{ oc.project.ibm }}'
  register: ibm_cs_operator_lookup
  until: ibm_cs_operator_lookup.resources[0].status.availableReplicas is defined
  retries: 10
  delay: 60

- name: Deploy - Phase 2 | Wait for operand-deployment-lifecycle-manager (ODLM) to be ready (60s delay)
  kubernetes.core.k8s_info:
    kind: Deployment
    api_version: apps/v1
    name: operand-deployment-lifecycle-manager
    namespace: '{{ oc.project.ibm }}'
  register: ibm_odlm_operator_lookup
  until: ibm_odlm_operator_lookup.resources[0].status.availableReplicas is defined
  retries: 10
  delay: 60

- name: Deploy - Phase 2 | Create an operandbindinfo for {{ oc.project.aidc }} namespace
  kubernetes.core.k8s:
    src: '{{ playbook_dir }}/output/ibm/ibm-odlm-operandrequest.yaml'
    state: present

- name: Deploy - Phase 2 | Wait for ibm-licensing-service-operator to be ready (60s delay)
  kubernetes.core.k8s_info:
    kind: Deployment
    api_version: apps/v1
    name: ibm-licensing-operator
    namespace: '{{ oc.project.ibm }}'
  register: ibm_ls_operator_lookup
  until: ibm_ls_operator_lookup.resources[0].status.availableReplicas is defined
  retries: 10
  delay: 60

- name: Deploy - Phase 2 | Wait for operandbindinfo to be 'Completed' (60s delay)
  kubernetes.core.k8s_info:
    api_version: operator.ibm.com/v1alpha1
    kind: OperandBindInfo
    name: ibm-licensing-bindinfo
    namespace: '{{ oc.project.ibm }}'
  register: ibm_odlm_operandbindinfo_lookup
  until:
    - ibm_odlm_operandbindinfo_lookup.resources[0].status.phase is defined
    - ibm_odlm_operandbindinfo_lookup.resources[0].status.phase == "Completed"
  retries: 10
  delay: 60
