---
- name: Post-deploy - Phase 1 | Create route for Keycloak
  kubernetes.core.k8s:
    src: '{{ playbook_dir }}/output/middlewares/keycloak-route.yaml'
    state: present

- name: Post-deploy - Phase 1 | Create routes for aidc-dispatch and aidc-studio
  kubernetes.core.k8s:
    src: '{{ playbook_dir }}/output/aidc/apps-routes.yaml'
    state: present

- name: Post-deploy - Phase 1 | Import manually settings for Keycloak
  pause:
    prompt: |

     Import manually the {{ playbook_dir }}/file/keycloak/aidc-realm.json file via the web UI.

     Please refer to the documentation for details.

     Press "return" to continue. Press "ctrl+c" and then "a" to abort.

- name: Post-deploy - Phase 1 | Create secret for Studio application
  kubernetes.core.k8s:
    src: '{{ playbook_dir }}/output/aidc/studio-app-secret.yaml'
    state: present

- name: Post-deploy - Phase 1 | Create secret for Dispatch application
  kubernetes.core.k8s:
    src: '{{ playbook_dir }}/output/aidc/dispatch-app-secret.yaml'
    state: present
