---
- name: Prepare | Add a public helm repository
  kubernetes.core.helm_repository:
    name: '{{ helm.repo_name }}'
    repo_url: '{{ helm.repo_url }}'
  when: helm.repo_private|bool == false

- name: Prepare | Add a private helm repository
  kubernetes.core.helm_repository:
    name: '{{ helm.repo_name }}'
    repo_url: '{{ helm.repo_url }}'
    repo_username: '{{ helm_auth.repo_username }}'
    repo_password: '{{ helm_auth.repo_password }}'
  when: helm.repo_private|bool == true
