---
- name: Prepare | Manifest for Keycloak
  template:
    src: '{{ keycloak_manifest.src }}'
    dest: '{{ keycloak_manifest.dest }}'
  loop_control:
    loop_var: keycloak_manifest
  loop:
    - { src: 'middleware-keycloak-values.yaml.j2', dest: '{{ playbook_dir }}/output/middlewares/keycloak-values.yaml' }
    - { src: 'middleware-keycloak-route.yaml.j2', dest: '{{ playbook_dir }}/output/middlewares/keycloak-route.yaml' }
  when: keycloak.enabled|bool == true

- name: Prepare | Manifest for Postgres (used by Keycloak)
  template:
    src: 'middleware-postgres-values.yaml.j2'
    dest: '{{ playbook_dir }}/output/middlewares/postgres-values.yaml'
  when: keycloak_db.enabled|bool == true

- name: Prepare | Manifest for MongoDB
  template:
    src: 'middleware-mongodb-values.yaml.j2'
    dest: '{{ playbook_dir }}/output/middlewares/mongodb-values.yaml'
  when: mongodb.enabled|bool == true

- name: Prepare | Manifests for IBM operators
  template:
    src: '{{ ibm_manifest.src }}'
    dest: '{{ ibm_manifest.dest }}'
  loop_control:
    loop_var: ibm_manifest
  loop:
    - { src: 'ibm-operatorgroup.yaml.j2', dest: '{{ playbook_dir }}/output/ibm/ibm-operatorgroup.yaml' }
    - { src: 'ibm-common-service-operator.yaml.j2', dest: '{{ playbook_dir }}/output/ibm/ibm-common-service-operator.yaml' }
    - { src: 'ibm-licensing-operator.yaml.j2', dest: '{{ playbook_dir }}/output/ibm/ibm-licensing-operator.yaml' }
    - { src: 'ibm-odlm-operandrequest.yaml.j2', dest: '{{ playbook_dir }}/output/ibm/ibm-odlm-operandrequest.yaml' }
  when: ibm.operator.enabled|bool == true

- name: Prepare | Manifests for AI Decision Coordination (Secrets)
  template:
    src: '{{ aidc_manifest.src }}'
    dest: '{{ aidc_manifest.dest }}'
  loop_control:
    loop_var: aidc_manifest
  loop:
    - { src: 'aidc-dispatch-app-secret.yaml.j2', dest: '{{ playbook_dir }}/output/aidc/dispatch-app-secret.yaml' }
    - { src: 'aidc-studio-app-secret.yaml.j2', dest: '{{ playbook_dir }}/output/aidc/studio-app-secret.yaml' }
    - { src: 'aidc-apps-routes.yaml.j2', dest: '{{ playbook_dir }}/output/aidc/apps-routes.yaml' }
    - { src: 'aidc-dispatch-app-deployment.yaml.j2', dest: '{{ playbook_dir }}/output/aidc/dispatch-app-deployment.yaml' }
    - { src: 'aidc-studio-app-deployment.yaml.j2', dest: '{{ playbook_dir }}/output/aidc/studio-app-deployment.yaml' }

